[build]
builder = "dockerfile"
dockerfilePath = "copypools-nextjs/Dockerfile"
dockerContext = "copypools-nextjs"

[deploy]
startCommand = "node server.js"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10
