[phases.setup]
cmds = ["npm install -g yarn"]

[phases.install]
cmds = ["yarn install --ignore-engines"]

[phases.build]
cmds = ["echo 'Ponder does not require build step'"]

[start]
cmd = "yarn start"

[variables]
NIXPACKS_NODE_VERSION = "20.18.0"
